Repository ViCCo-Group/thingsvision, pull requests merged in 2024-03, with the labels that each got.

#156 adding the other versions of dreamsim
  README.md
  docs/AvailableModels.md
  tests/helper.py
  thingsvision/custom_models/dreamsim/dreamsim.py
Labels: documentation, enhancement

#157 Fixed TorchvisionExtractor model_parameters
  tests/helper.py
  thingsvision/core/extraction/extractors.py
Labels: cleanup

#158 added alignment method to extractor for aligning representations using gLocal
  README.md
  docs/Alignment.md
  docs/RSA.md
  tests/extractor/extraction/test_pretrained_model.py
  tests/helper.py
  thingsvision/_version.py
  thingsvision/core/extraction/base.py
  thingsvision/core/extraction/extractors.py
  thingsvision/core/extraction/helpers.py
  thingsvision/core/extraction/torch.py
  thingsvision/utils/alignment/__init__.py
  thingsvision/utils/alignment/transforms.py
Labels: enhancement, cleanup
