Repository ViCCo-Group/thingsvision, pull requests merged in 2024-04, with the labels that each got.

#159 refactored batch-wise feature extraction and added explanation to README and the docs
  README.md
  docs/Alignment.md
  docs/AvailableModels.md
  docs/GettingStarted.md
  tests/extractor/extraction/test_torch_vs_tensorflow.py
  tests/helper.py
  thingsvision/_version.py
  thingsvision/core/extraction/base.py
  thingsvision/core/extraction/extractors.py
  thingsvision/core/extraction/helpers.py
  thingsvision/core/extraction/tensorflow.py
  thingsvision/core/extraction/torch.py
Labels: documentation, cleanup

#160 implemented mini-batch extraction with with statement for PyTorch
  README.md
  docs/GettingStarted.md
  tests/extractor/extraction/test_torch_vs_tensorflow.py
  thingsvision/_version.py
  thingsvision/core/extraction/torch.py
Labels: enhancement

#161 added mae vits
  README.md
  docs/index.md
  tests/helper.py
  thingsvision/_version.py
  thingsvision/core/extraction/extractors.py
  thingsvision/core/extraction/torch.py
  thingsvision/utils/models/mae/__init__.py
  thingsvision/utils/models/mae/utils.py
  thingsvision/utils/models/mae/vit_mae.py
Labels: enhancement

#163 Small fix for the show-model CLI functionality
  thingsvision/thingsvision.py
Labels: bug, cleanup

#164 Bug fix for the extract-features CLI functionality
  thingsvision/thingsvision.py
Labels: bug, cleanup

#166 updating requirements
  requirements.txt
  setup.py
Labels: enhancement

#167 CKA speedups + PyTorch 2.0+ support
  README.md
  docs/RSA.md
  docs/index.md
  requirements.txt
  setup.py
  tests/helper.py
  tests/test_features.py
  tests/test_rest.py
  thingsvision/_version.py
  thingsvision/core/cka/__init__.py
  thingsvision/core/cka/base.py
  thingsvision/core/cka/cka_base.py
  thingsvision/core/cka/cka_numpy.py
  thingsvision/core/cka/cka_torch.py
  thingsvision/core/cka/helpers.py
Labels: documentation, enhancement

#168 implemented automatic type conversion between numpy and torch
  README.md
  tests/helper.py
  tests/test_features.py
  tests/test_rest.py
  thingsvision/_version.py
  thingsvision/core/cka/cka_torch.py
Labels: enhancement

#169 added option to average-pool tokens and concat with `[cls]` token
  README.md
  docs/AvailableModels.md
  docs/CustomModels.md
  tests/helper.py
  thingsvision/_version.py
  thingsvision/core/extraction/base.py
  thingsvision/core/extraction/extractors.py
  thingsvision/core/extraction/helpers.py
  thingsvision/core/extraction/torch.py
Labels: enhancement

#171 Update torch.py
  thingsvision/_version.py
  thingsvision/core/extraction/torch.py
Labels: enhancement
